services:
  db:
    image: postgres:16-alpine
    container_name: postgres_local
    environment:
      POSTGRES_DB: costos
      POSTGRES_USER: costos_user
      POSTGRES_PASSWORD: costos_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_local_data:/var/lib/postgresql/data

volumes:
  postgres_local_data:
